# Generated by Django 5.1.4 on 2024-12-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'indexes': [models.Index(fields=['name'], name='branch_index')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Employment Type',
                'verbose_name_plural': 'Employment Types',
                'indexes': [models.Index(fields=['name'], name='employment_type_index')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'indexes': [models.Index(fields=['name'], name='location_index')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='website')),
                ('branch', models.ManyToManyField(blank=True, to='job_db.branch', verbose_name='branch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_db.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'qualifications',
                'indexes': [models.Index(fields=['name'], name='qualification_index')],
            },
        ),
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, unique=True, verbose_name='link')),
                ('job_title', models.CharField(max_length=255, verbose_name='job title')),
                ('date_scraped', models.DateTimeField(auto_now_add=True, verbose_name='date scraped')),
                ('direct_apply', models.BooleanField(default=False, verbose_name='direct apply')),
                ('home_office', models.BooleanField(default=False, verbose_name='home office')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='job description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_db.company', verbose_name='company')),
                ('employment_type', models.ManyToManyField(blank=True, to='job_db.employmenttype', verbose_name='employment type')),
                ('location', models.ManyToManyField(blank=True, to='job_db.location', verbose_name='location')),
                ('qualification', models.ManyToManyField(blank=True, to='job_db.qualification', verbose_name='qualification')),
            ],
            options={
                'verbose_name': 'Job Advertisement',
                'verbose_name_plural': 'Job Advertisements',
                'ordering': ['-date_scraped'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_index'),
        ),
        migrations.AddIndex(
            model_name='jobadvertisement',
            index=models.Index(fields=['link'], name='job_link_index'),
        ),
        migrations.AddIndex(
            model_name='jobadvertisement',
            index=models.Index(fields=['job_title'], name='job_title_index'),
        ),
    ]
